---
- block:

    - name: Read JSON file
      ansible.builtin.include_vars:
        file: networkconfig/networkconfigexample.json
        name: networkconfig

    - name: Set facts from networkconfig
      ansible.builtin.set_fact:
        peer_organisations: "{{ networkconfig | json_query('networkConfig.peerOrganisations[*]')}}"
        orderer_organisations: "{{ networkconfig | json_query('networkConfig.ordererOrganisations[*]')}}"
        admin_orderer_orgs: []
        admin_peer_orgs: []
        peer_orgs: []
        identities: []
        orderer_orgs_prep: []
        orderer_orgs: []
        orderers: []
        orderers_prep: []
        externalorderers: []
        ordererendpoints: []
        certificates: []
        metadata_name: "demo"
        spec_name: "demo"


    - name: Setting up configuration for peer orgs
      ansible.builtin.set_fact:
          admin_peer_orgs: "{{ admin_peer_orgs + [{'mspid': item.0.mspid}] }}"
          peer_orgs: "{{ peer_orgs + [{'mspid': item.0.mspid, 'caname': item.1.name, 'canamespace': 'default'}] }}"
          identities: "{{ identities + [{'mspid': item.0.mspid, 'secretkey': 'user.yaml', 'secretname': (item.0.mspid | lower) ~ '-admin', 'secretnamespace': 'default'}] }}"
      loop: "{{ peer_organisations | subelements('certificateAuthorities') }}"

    - name: Collecting orderer mspids and setting up identities
      ansible.builtin.set_fact:
        admin_orderer_orgs: "{{admin_orderer_orgs + [{'mspid': item.mspid}]}}"
        identities: "{{ identities + [{'mspid': item.mspid, 'secretkey': 'user.yaml', 'secretname': 'orderer-' ~ (item.mspid | lower) ~ '-admin-tls', 'secretnamespace': 'default'}] }}"
      loop: "{{orderer_organisations}}"
    
    - name: Adding orderer sign identities
      ansible.builtin.set_fact:
        identities: "{{ identities + [{'mspid': (item.mspid)~'-sign' , 'secretkey': 'user.yaml', 'secretname': 'orderer-' ~ (item.mspid | lower) ~ '-admin-sign', 'secretnamespace': 'default'}] }}"
      loop: "{{orderer_organisations}}"
      
    - name: Collecting orderer orgs
      ansible.builtin.set_fact:
        orderer_orgs_prep: "{{ orderer_orgs + [{'mspid': item.0.mspid, 'caname': item.1.name, 'canamespace': 'default'}] }}"
      loop: "{{ orderer_organisations | subelements('certificateAuthorities') }}"

    - name: fetching orderer data
      include_tasks: fetching_certs.yaml
      loop: "{{ networkconfig.networkConfig.ordererOrganisations }}"
      loop_control:
        loop_var: org

    - name: Generate YAML file from template
      ansible.builtin.template:
        src: "templates/MainChannel/template/main_channel_template.yaml.j2"
        dest: "templates/MainChannel/generatedConfigs/{{ metadata_name }}.yaml"


    - name: Apply mainchannel file 
      shell: kubectl apply -f templates/MainChannel/generatedConfigs/{{ metadata_name }}.yaml