# kubectl hlf ca create --storage-class=standard --capacity=1Gi --name=org1-ca \
#    --enroll-id=enroll --enroll-pw=enrollpw --hosts=org1-ca.localho.st --istio-port=443
---
- name: create cas
  hosts: localhost
  tasks:
    - name: Read JSON file
      ansible.builtin.include_vars:
        file: networkconfig/networkconfigexample.json
        name: networkconfig

    - name: Get ca parameters
      ansible.builtin.set_fact:
        peer_ca: "{{ networkconfig | json_query('networkConfig.peerOrganisations[*].certificateAuthorities[*][]')}}"
        orderer_ca: "{{ networkconfig | json_query('networkConfig.ordererOrganisations[*].certificateAuthorities[*][]')}}"

    
    - name: Print detected configuration for peer-orgs
      debug:
        msg: "{{ item }}"
      loop: "{{ peer_ca}}"

    - name: Print detected configuration for orderer-orgs
      debug:
        msg: "{{ item }}"
      loop: "{{ orderer_ca}}"
