---
- name: Deploy all configured orderers from network config
  hosts: localhost
  tasks:
    - name: Read JSON file
      ansible.builtin.include_vars:
        file: networkconfig/networkconfigexample.json
        name: networkconfig
      
    - name: Load all orderer organisations from network config
      ansible.builtin.set_fact:
        orderer_organisations: "{{ networkconfig | json_query('networkConfig.ordererOrganisations[*]')}}"

    - name: Print orderer organisations
      debug:
        msg: "{{ item }} "
      with_items: "{{ orderer_organisations }}"

    - name: Register user orderer
      command : kubectl hlf ca register --name={{ item.certificateAuthorities[0].name }} --user=orderer --secret=ordererpw --type=orderer --enroll-id=enroll --enroll-secret=enrollpw --mspid={{item.mspid}}
      loop: "{{ orderer_organisations}}"
      ignore_errors: true

    - name: Deploy each orderer of each organization
      command: kubectl hlf ordnode create --image=hyperledger/fabric-orderer --version=2.4.6 --storage-class=standard --enroll-id=orderer --mspid={{ item.0.mspid}} --enroll-pw=ordererpw --capacity={{item.1.capacity}} --name={{item.1.name}}
       --ca-name={{item.1.caname}} --hosts={{item.1.hosts}} --istio-port={{item.1.istioport}}
      loop: "{{ orderer_organisations | subelements('orderers') }}"