# kubectl hlf ca register --name=ord-ca --user=orderer --secret=ordererpw \
#   --type=orderer --enroll-id enroll --enroll-secret=enrollpw --mspid=OrdererMSP --ca-url="https://ord-ca.localho.st:443"

# kubectl hlf ordnode create --image=$ORDERER_IMAGE --version=$ORDERER_VERSION \
#    --storage-class=standard --enroll-id=orderer --mspid=OrdererMSP \
#    --enroll-pw=ordererpw --capacity=2Gi --name=ord-node1 --ca-name=ord-ca.default \
#    --hosts=orderer0-ord.localho.st --istio-port=443

---
- name: Deploy all configured orderers from network config
  hosts: localhost
  tasks:
    - name: Read JSON file
      ansible.builtin.include_vars:
        file: networkconfig/networkconfigexample.json
        name: networkconfig
      
    - name: Load all orderer organisations from network config
      ansible.builtin.set_fact:
        orderer_organisations: "{{ networkconfig | json_query('networkConfig.ordererOrganisations[*]')}}"

    - name: Print orderer organisations
      debug:
        msg: "{{ item }} "
      with_items: "{{ orderer_organisations }}"

    - name: Register user orderer
      command : kubectl hlf ca register --name={{ item.certificateAuthorities[0].name }} --user=orderer --secret=ordererpw --type=orderer --enroll-id=enroll --enroll-secret=enrollpw --mspid={{item.mspid}}
      loop: "{{ peer_organisations}}"
      ignore_errors: true

    - name: Deploy each orderer of each organization
      command: kubectl hlf orderer create --statedb=couchdb --image=hyperledger/fabric-orderer --version=2.4.6--storage-class=standard --enroll-id=orderer --mspid={{ item.0.mspid }} --enroll-pw=ordererpw --capacity= {{item.1.capacity}} --name={{item.1.name}}
       --ca-name={{item.1.caname}} --hosts={{item.1.hosts}} --istio-port={{item.1.istioport}}
      loop: "{{ peer_organisations | subelements('peers') }}"