apiVersion: hlf.kungfusoftware.es/v1alpha1
kind: FabricFollowerChannel
metadata:
  name: mychannel-Org1MSP
spec:
  
  anchorPeers:
    - host: peer0-org1.localho.st
      port: 443
    - host: peer1-org1.localho.st
      port: 443
    
  hlfIdentity:
    secretKey: Org1MSP.yaml
    secretName: wallet-org1msp
    secretNamespace: default

  mspId: Org1MSP
  name: mychannel
  externalPeersToJoin: []
  orderers:
    - certificate: |
            -----BEGIN CERTIFICATE-----
        MIIC1zCCAn6gAwIBAgIUQ5CD+Vur+2qFJ5uTeFyanKE//sUwCgYIKoZIzj0EAwIw
        bTELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj
        YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEO
        MAwGA1UEAxMFdGxzY2EwHhcNMjQwNDE2MTQyNjM0WhcNMjUwNDE3MTQ1MTAwWjAk
        MRAwDgYDVQQLEwdvcmRlcmVyMRAwDgYDVQQDEwdvcmRlcmVyMFkwEwYHKoZIzj0C
        AQYIKoZIzj0DAQcDQgAEAg+onkmA6TGOep4DFe5N6FLBkqb79N0HmbMttyg7Rzmu
        a/sDHvjit5c1XjRIA94dK1bzbqkUBQ7zo6vFQB64q6OCAUMwggE/MA4GA1UdDwEB
        /wQEAwIDqDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/
        BAIwADAdBgNVHQ4EFgQUAmrppwhPqTh5LbVvWReK7Ro9DVIwKwYDVR0jBCQwIoAg
        kY5qxgciAxY/TdsuAKeuY70jtKVq/IpFtVbMGHvLm/IwVwYDVR0RBFAwToIJbG9j
        YWxob3N0gglvcmQtbm9kZTGCEW9yZC1ub2RlMS5kZWZhdWx0ghdvcmRlcmVyMC1v
        cmQubG9jYWxoby5zdIcEfwAAAYcErBIAAjBbBggqAwQFBgcIAQRPeyJhdHRycyI6
        eyJoZi5BZmZpbGlhdGlvbiI6IiIsImhmLkVucm9sbG1lbnRJRCI6Im9yZGVyZXIi
        LCJoZi5UeXBlIjoib3JkZXJlciJ9fTAKBggqhkjOPQQDAgNHADBEAiAsTczQIpVn
        QdI336tDRQF/pTcNvYfA9KjXlB+zFmpelgIgPNI4o617IKhdjjc9pr7Sg7X+etfg
        ycTrBIbqZhuX6LQ=
        -----END CERTIFICATE-----
      url: grpcs://ord-node1.default:7050
        
  peersToJoin:
    - name: org1-peer0
      namespace: default
    - name: org1-peer1
      namespace: default
    
